import Header from '@/components/header'

export default function Home() {
  return (
    <div>
      <Header />
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
      <p>rrr</p>
    </div>
  )
}
